// Generated by CoffeeScript 1.10.0
(function() {
  if (window.OButton == null) {
    window.OButton = {};
  }

  window.$ = window.$.noConflict(true);

  console.log('Main.js: JQuery ' + $.fn.jquery + ' Handlebars: ' + Handlebars.VERSION);

}).call(this);
