// Generated by CoffeeScript 1.10.0
(function() {
  var isFirstTimeClick, module, name;

  if (OButton) {
    console.log('OButton initialized');
    for (name in OButton) {
      module = OButton[name];
      console.log("OButton." + name + " initialized");
      if (typeof module.initialize === "function") {
        module.initialize();
      }
    }
    isFirstTimeClick = true;
    console.log('kango.addMessageListener');
    kango.addMessageListener('click', (function(_this) {
      return function(event) {
        console.log('click');
        for (name in OButton) {
          module = OButton[name];
          console.log('Module.click:', name, module);
          if (isFirstTimeClick) {
            if (typeof module.onceOnClick === "function") {
              module.onceOnClick();
            }
          }
          if (typeof module.onClick === "function") {
            module.onClick();
          }
        }
        return isFirstTimeClick = false;
      };
    })(this));
  } else {
    console.log('OButton not initialized');
  }

}).call(this);
